name: h3pandas-env
channels: 
  - conda-forge
dependencies:
  # Required
  - python>=3.9
  - shapely
  - geopandas>=0.9.*
  - pandas
  # Notebooks
  - matplotlib
  # Pip
  - pip
  - pip:
    # Installing through pip to avoid segfault on Apple Silicon
    # https://github.com/uber/h3-py/issues/313
    - h3==3.7.6
