name: h3pandas-env
channels: 
  - conda-forge
dependencies:
  # Required
  - python=3.9
  - shapely
  - h3-py=3.6.*
  - geopandas=0.9.*
  - pandas
  # Test
  - pytest
  - pytest-cov
  # Notebooks
  - matplotlib
