name: h3pandas-env
channels: 
  - conda-forge
dependencies:
  - python=3.8
  - shapely=1.7.*
  - h3-py=3.6.*
  - geopandas=0.9.*
  - pandas=1.2.*
  - pytest=6.2.*
  - pytest-cov=2.12.*
  - matplotlib=3.3.*
  - typing-extensions=3.10.*
