name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: myenv
        environment-file: environment.yml
    
    - name: Install development dependencies
      shell: bash -l {0}
      run: |
        conda env update --file environment-dev.yml
    
    - name: ruff check
      shell: bash -l {0}
      run: |
        ruff check .
    
    - name: pytest
      shell: bash -l {0}
      run: |
        pytest tests/
